---
- name: "Install docker-ce-cli (debian)"
  apt:
    pkg: "{{ install_docker_ce_cli_packages[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] | json_query('[].name')}}"
    update_cache: yes
    install_recommends: no
  register: installed_docker_ce_cli_packages
  tags:
    - "docker-ce-cli"
- name: "Pin docker-ce-cli (debian)"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
  shell: >-
    apt-mark hold {{ item }}
  with_items: "{{ install_docker_ce_cli_packages[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] | json_query('[?hold==`true`].name')}}"
  when:
    - "installed_docker_ce_cli_packages.changed"
  tags:
    - "docker-ce-cli"
